### ISSUE TITLE
Input fields adding focus-visible on click

### ISSUE THREAD

**Issue by iandevlin** [WICG/focus-visible#131]
Hi, I noticed that on Chrome and Firefox at least, the `focus-visible` class gets added to `textarea` and `input` fields even when the user uses the mouse to get focus.
Is this expected behaviour? I would've thought not but I may have missed something.

(It happens on the demo page: https://wicg.github.io/focus-visible/demo/)

**Comment by robdodson** [comment]
Yes it's expected behavior, meant to match the way that the browser works today. For instance, if you mouse click a `<button>` in Chrome it will not draw a focus indicator, but if you mouse click a `<input type=text>` it will. I believe the basis of this assumption is that for any area where it's assumed the user is going to provide keyboard input, the browser will draw a focus indicator.

In [the spec](https://drafts.csswg.org/selectors-4/#the-focus-visible-pseudo) this is articulated in the second half of the opening statement:

> The :focus-visible pseudo-class applies while an element matches the :focus pseudo-class **and the UA determines via heuristics that the focus should be made evident on the element**.

> For example, UAs typically display focus indicators on text fields any time they’re focused, to draw attention to the fact that keyboard input will affect their contents.

> On the other hand, UAs typically only display focus indicators on buttons when they were focused by a keyboard interaction (such as tabbing through the document)—because it’s not always immediately obvious where the focus has gone after such an interaction, but is sufficiently self-evident when the button was focused by more obviously-targetted interactions, like clicking on the button with a mouse pointer.

**Comment by iandevlin** [comment]
Ok cool, thanks very much for the explanation. That went past me for some reason, I assumed that they would all act the same.
