### ISSUE TITLE
How to import the init function from focus-visible? Can it be a module?

### ISSUE THREAD

**Issue by renojvarghese** [WICG/focus-visible#163]
Hi. I was wondering how I could import just the init function.  I am using this polyfill as a node module, and I have some things that need to be checked before utilizing the focus-visible polyfill. I was looking for a module.exports, but could not find one in the src code

**Comment by robdodson** [comment]
We did not structure the original polyfill as a module, but with the widespread support of ES Modules we should probably update it to be one.

A temporary workaround if you don't feel like modifying the source would be to include the script async using a bit of JavaScript.

```js
var polyfill = document.createElement('script'); 
polyfill.src = "https://my-site.com/scripts/focus-visible.min.js";
var script = document.getElementsByTagName('script')[0];
script.parentNode.insertBefore(polyfill, script);
```

**Comment by renojvarghese** [comment]
Thanks. Works well, but I ended copying and pasting the init function into my own js file. Really enjoyed this polyfill. It was exactly what I was looking for in that I didn't have to decide between one user experience over another

**Comment by robdodson** [comment]
Glad to hear it helped! I'll leave this issue open and edit the title so we know to come back and work on an exportable module.

**Comment by renojvarghese** [comment]
Mind if I take a stab at it? I think I might know how to do it such that it will work in both the browser and as a node module

**Comment by robdodson** [comment]
@renojvarghese sure thing! Maybe you were thinking the same thing, but we'd want it to be an ES Module so folks could use standard `import` to pull it in.

**Comment by renojvarghese** [comment]
@robdodson ^^^ Is this what you mean?

**Comment by robdodson** [comment]
Hi @renojvarghese, sorry for my total lack of oversight, but I just realized that we're already exporting the distribution of focus-visible with a module friendly wrapper (look at the source for dist/focus-visible.js).

Also, to better answer your original question... rather than importing the init function, I would recommend dynamically importing the entire module. You can do this with ES modules using dynamic [`import()` syntax](https://developers.google.com/web/updates/2017/11/dynamic-import)

```
if (someCondition) {
  import('./node_modules/focus-visible/dist/focus-visible.min.js')
	.then(_ => console.log('focus-visible loaded!'));
}
```

If you're using Node's `require` syntax, it has a similar dynamic mechanism.

```
if (someCondition) {
  require('focus-visible');
}
```

The reason I recommend dynamically importing the entire module, instead of importing the init function, is because when focus-visible ships in all browsers, you'll only need to update your CSS to use `:focus-visible` instead of `.focus-visible`. Whereas, if you're importing the `init` function, you'd need to delete any places you call `init` because the native CSS feature won't have a JS `init` function. It may end up being about the same amount of work either way, but I think we're going to advise this approach from now on.

**Comment by renojvarghese** [comment]
@robdodson I see what you mean. I checked the code in this repo, but not the node_module. Loading focus visible on a condition is better. Thanks for the explanation :D
