### ISSUE TITLE
Option to add class to body when any element on the page has focus-visible

### ISSUE THREAD

**Issue by chinanderm** [WICG/focus-visible#207]
Feature suggestion: When _any_ element on the page has focus-visible, can there be a config option (or default) to also had a class to the body indicating that the user is navigating via keyboard?

The use case here is to display not-currently-focused elements that may be hidden behind hovers or other UI/UX patterns.

An example of this functionality is Dropbox. If you navigate to a list of files and start tabbing, you'll see some UI elements appear that would only normally show when hovered.

I would think that adding a line to addFocusVisibleClass() and removeFocusVisibleClass() to add/remove the body class would suffice. I'd be happy to submit a PR if that would help.

**Comment by robdodson** [comment]
I agree that functionality sounds useful. However, I'm not sure if this polyfill is the best place to add it. Ideally the polyfill should have parity with the CSS property and the native version of `:focus-visible` would not be able to add this class to body. So it would lead to a situation where some apps might not be able to remove the polyfill because they're relying on non-standard behavior.

I think I'm going to close this issue for now but happy to keep discussing.

**Comment by Justineo** [comment]
I have another use case for this feature request. When used with frameworks like React/Vue, any direct modification can be discarded when the view is updated after the underlying data changes. So applying a class name flag to the root element may be a safer approach for these cases.

But I also agree that relying on this behavior will make it harder to switch to the native implementation.
