### ISSUE TITLE
focus visible triggers for mouse on inputs

### ISSUE THREAD

**Issue by mikey0000** [WICG/focus-visible#221]
focusTriggersKeyboardModality triggers on mouse down so users see a brief flash of outline or box-shadow.

this should be configurable as for the specific project we don't want focus on mouse anything

**Comment by robdodson** [comment]
>focusTriggersKeyboardModality triggers on mouse down so users see a brief flash of outline or box-shadow.

This is by design. The `:focus-visible` pseudo class uses a heuristic to determine which elements should always match focus. `input` fields are one such type of element. The explainer may help more here: https://github.com/WICG/focus-visible/blob/master/explainer.md

> this should be configurable as for the specific project we don't want focus on mouse anything

This is a polyfill for the upcoming `:focus-visible` pseudo class which is not configurable. You might check out a library like [what-input](https://github.com/ten1seven/what-input) if you want more control.

**Comment by MaxMaeder** [comment]
@mikey0000 I ran into a similar issue, so I made a library that does exactly that.

If you're interested, you can find it [here](https://github.com/MaxMaeder/keyboardFocus.js).
