### ISSUE TITLE
How should I use this with Create react app?

### ISSUE THREAD

**Issue by TheKnarf** [WICG/focus-visible#230]
Do I have to edit my html-file, or could I include it from `src/index.js`?

**Comment by robdodson** [comment]
Hey @TheKnarf 

I'm not very familiar with React but it looks like some folks have made a Hook to do this
https://github.com/WICG/focus-visible/issues/205

You could also see about importing it from src/index.js. After it's been loaded onto the page it should "just work" by setting `.inert` to true or false on the DOM elements. But using something like a Hook might be more idiomatic React style and may work better if React tries to override stuff (like if React removes the attribute because it didn't add it).
